Swuber/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Swuber.Models;

namespace Swuber.Controllers
{
    public class CustomersController : Controller
    {
        private SWOOPEntities db = new SWOOPEntities();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerID,FirstName,LastName,Phone,Tag,Password,NNumber,TagColor,Rating,Status")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,FirstName,LastName,Phone,Tag,Password,TagColor,Rating,Status")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Swuber/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Swuber.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Chat()
        {
            return View();
        }
        public ActionResult ChatWalker()
        {
            return View();
        }
    }
}

Swuber/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3 style="text-align:center;"><i>Mission: “To make parking more manageable and campus a smaller place; solving a walking problem by fixing a parking problem. Fast, quick, and easy. A spot for a driver with a maximum 5 minute wait."</i></h3>
<p style="text-align:center;" >We started as a project in April 2017 for a web programming class at the Univeristy of North Florida</p>
<br />

<div class="row">
    <div class="col-md-4">
        <img src="~/Images/about1.png" border="0" width="300" height="300">
        <h4>Less Walking</h4>

        <p>Too hot? Storming outside? No problem! With our app, you can now be picked up by another student who is in need of a parking spot. So not only does help them out, it saves you the long trek across campus.</p>

    </div>
<div class="col-md-4">
    <img src="~/Images/about2.png" border="0" width="300" height="300">
        <h4>More Parking</h4>
        <p>You don't need to circle around the parking lot 10 times just to find a spot or follow a person around just to find out they are getting something from their car and not actually leaving. Just connect with another student 
    leaving campus, pick them up, and you got yourself a hassle-free place to park your vehicle!</p>

    </div>
<div class="col-md-4">
    <img src="~/Images/about3.png" border="0" width="300" height="300">
        <h4>Happy Campus</h4>
        <p>We strive to provide a much-needed service to the Alumni and current students at the University of North Florida regarding parking. Our website gives the students the ability to assist each other in finding the best parking spot available while charging no fees to encourage engagement in the community</p>

    </div>

    
</div>
<br />
<h5 style="text-align:center;">{ Some videos on UNF's parking problem to help you understand WHY you need Swuber in your life. }</h5>
<br />
<br />
<iframe width="560" height="315" src="https://www.youtube.com/embed/NvAXu6vdZAU" frameborder="0" allowfullscreen></iframe>   <iframe width="560" height="315" src="https://www.youtube.com/embed/ztYm3dFPyF8" frameborder="0" allowfullscreen></iframe>

Swuber/Views/Home/Chat.cshtml
@{
    ViewBag.Title = "Chat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chat</h2>
<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            var str = "(driver)";
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name,message) {
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + str+ htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:'));
//lets hard code whether walker and put a comma.
//they fill in their name from there.
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(),$('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

Swuber/Views/Home/ChatWalker.cshtml
@{
    ViewBag.Title = "ChatWalker";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ChatWalker</h2>


<h2>Chat</h2>
<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            var str = "(walker)";
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name,message) {
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + str+ htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:'));
//lets hard code whether walker and put a comma.
//they fill in their name from there.
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(),$('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

Swuber/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3 style="text-align:center;"><i>Questions? Comments? Concerns?</i></h3>
<p style="text-align:center"><img src="~/Images/SWOOPCO.jpg" border="0" width="200" height="50"></p>
<address style="text-align:center">
    One UNF Drive<br />
    Jacksonville, Fl 32224<br />
    <abbr title="Phone">P:</abbr>
    555.555.0100
</address>
<br />

<div class="row">
    <div class="col-md-4">
        <img src="~/Images/support.png" border="0" width="200" height="200">
        <h4>Support</h4>

        <strong>Support:</strong>   <a href="mailto:Support@swuber.com">Support@swuber.com</a><br />

    </div>
    <div class="col-md-4">
        <img src="~/Images/marketing.png" border="0" width="200" height="200">
        <h4>Marketing</h4>

        <strong>Marketing:</strong> <a href="mailto:Marketing@swuber.com">Marketing@swuber.com</a>
    </div>
    <div class="col-md-4">
        <img src="~/Images/advertising.png" border="0" width="200" height="200">
        <h4>Advertising</h4>

        <strong>Advertising:</strong><a href="mailto:Advertising@swuber.com">Advertising@swuber.com</a>

    </div>

</div>

Swuber/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    
    <h1>A new way to find the best parking at the University of North Florida</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>@Html.ActionLink("Register", "Create", "Customers")<img src="~/Images/registerlogo.png" border="0" width="50" height="50"></h2>

        <p>New user? Click here to create an account</p>
        
    </div>
    <div class="col-md-4">
       
        <h2>@Html.ActionLink("Login", "Login", "Login")<img src="~/Images/loginlogo.png" border="0" width="50" height="50"></h2>
        <p>Existing user? Click here to sign in</p>
        
    </div>
    <div class="col-md-4">
      
        <h2>@Html.ActionLink("Chat", "Chat")<img src="~/Images/chatlogo.png" border="0" width="50" height="50"></h2>
        <p>Chat with us here</p>
        
    </div>
    <a class="twitter-timeline" href="https://twitter.com/SwuberCorp">Tweets by SwuberCorp</a>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>